version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: ./Dockerfile
    container_name: web-app
    ports:
      - "8000:8000"
    depends_on:
      - db
      - minio
    env_file:
      - .env
    networks:
      - app-network

  db:
    image: postgres:latest
    container_name: postgres
    environment:
      POSTGRES_DB: "${DATABASE__DB}"
      POSTGRES_USER: "${DATABASE__USERNAME}"
      POSTGRES_PASSWORD: "${DATABASE__PASSWORD}"
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - app-network

  minio:
    image: minio/minio
    container_name: minio
    environment:
      MINIO_ROOT_USER: "${MINIO__ROOT_USER}"
      MINIO_ROOT_PASSWORD: "${MINIO__ROOT_PASSWORD}"
    volumes:
      - miniodata:/data
    ports:
      - "9000:9000"
    command: server /data
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: 30s
      timeout: 20s
      retries: 3
    networks:
      - app-network

volumes:
  pgdata:
  miniodata:

networks:
  app-network:
    driver: bridge
