version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: ./Dockerfile
    container_name: web-app
    ports:
      - "8000:8000"
    depends_on:
      - db
    env_file:
      - .env
    networks:
      - app-network

  db:
    image: postgres:latest
    container_name: postgres
    environment:
      POSTGRES_DB: "${DATABASE__DB}"
      POSTGRES_USER: "${DATABASE__USERNAME}"
      POSTGRES_PASSWORD: "${DATABASE__PASSWORD}"
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - app-network

volumes:
  pgdata:

networks:
  app-network:
    driver: bridge
