"""Add a table of memes

Revision ID: 42e69c483289
Revises: dd4f1d846c52
Create Date: 2024-06-20 08:38:56.388432

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '42e69c483289'
down_revision: Union[str, None] = 'dd4f1d846c52'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('meme',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('description', sa.String(length=512), nullable=True),
    sa.Column('image_url', sa.String(length=512), nullable=False),
    sa.Column('visibility', sa.Boolean(), nullable=False),
    sa.Column('owner_id', sa.Uuid(as_uuid=False), nullable=False),
    sa.ForeignKeyConstraint(['owner_id'], ['user.user_id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('meme')
    # ### end Alembic commands ###
