"""change the on_delete property

Revision ID: 5644ecaa639c
Revises: 42e69c483289
Create Date: 2024-06-20 10:04:46.870191

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5644ecaa639c'
down_revision: Union[str, None] = '42e69c483289'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('meme_owner_id_fkey', 'meme', type_='foreignkey')
    op.create_foreign_key(None, 'meme', 'user', ['owner_id'], ['user_id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'meme', type_='foreignkey')
    op.create_foreign_key('meme_owner_id_fkey', 'meme', 'user', ['owner_id'], ['user_id'], ondelete='SET NULL')
    # ### end Alembic commands ###
